package com.example.chtl.compilers.chtl;

public enum ChtlTokenType {
	// 界符
	LBRACE, RBRACE, LBRACKET, RBRACKET, LPAREN, RPAREN,
	COLON, EQUAL, SEMICOLON, COMMA, DOT, HASH, AT, AMP,

	// 文字
	IDENT, STRING, NUMBER,

	// 关键字（按文档）
	KW_TEXT, KW_STYLE, KW_SCRIPT,
	KW_TEMPLATE, KW_CUSTOM, KW_ORIGIN, KW_IMPORT, KW_NAMESPACE,
	KW_INHERIT, KW_DELETE, KW_INSERT,
	KW_AFTER, KW_BEFORE, KW_REPLACE, KW_ATTOP, KW_ATBOTTOM,
	KW_FROM, KW_AS, KW_EXCEPT,

	// 其他
	EOF
}