package com.chtl.lexer;

public enum State {
	DEFAULT,
	IN_NAMESPACE,
	IN_TEMPLATE_STYLE,
	IN_TEMPLATE_ELEMENT,
	IN_TEMPLATE_VAR,
	IN_CUSTOM_STYLE,
	IN_CUSTOM_ELEMENT,
	IN_CUSTOM_VAR,
	IN_ORIGIN_HTML,
	IN_ORIGIN_STYLE,
	IN_ORIGIN_JS,
	IN_IMPORT,
	IN_CONFIGURATION,
	IN_NAME_BLOCK,
	IN_STYLE_BLOCK,
	IN_SCRIPT_BLOCK,
	IN_ELEMENT_BLOCK,
	IN_TEXT_BLOCK
}